
version: '3.8'

networks:
  intra:
    driver: bridge
    name: intra
    
volumes:
  md-data:
          driver: local
          driver_opts:
                  type: none 
                  o: bind
                  device: /home/bcho/data/mariadb
  wp-data:
          driver: local
          driver_opts:
                  type: none
                  o: bind 
                  device: /home/bcho/data/wordpress

services:
  mariadb:
    image: mariadb
    pull_policy: never
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - md-data:/var/lib/mysql
    networks:
      - intra
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress
    pull_policy: never
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - intra
    env_file:
      - .env
    restart: always
    expose:
      - "9000"

  nginx:
    image: nginx
    pull_policy: never
    depends_on:
      - wordpress
    container_name: nginx
    build: requirements/nginx
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - intra
    env_file:
      - .env
    restart: always 
    ports:
      - "443:443"
